### PR TITLE
Add support for existing data layer

### PR DESCRIPTION
**Pull request by sprankhub**
E.g. useful for the Optimize anti-flicker snippet
See https://developers.google.com/optimize

### CODE REVIEW

**Comment by jissereitsma** [comment]
Nice addition. Thanks!

**Comment by jissereitsma** [comment]
Included in release 1.1.2.

**Comment by sprankhub** [comment]
Thanks! 1.1.2 does not match the current releases though and I do not see a new release after the merge. Could you please double check?

**Comment by jissereitsma** [comment]
I was working in too many repos at the same time. Release 1.6.4 now includes your fix.

**Pull request merged**
