### PR TITLE
Added bundle price support

### PR DESCRIPTION
**Pull request by Basvkempen**

### CODE REVIEW

**Comment by jissereitsma** [comment]
Thanks for contributing! This looks like a nice addition. However, you included also 3 files from your PhpStorm environment (`.idea`). Could you modify your PR so those files are excluded? After that, I'll merge right away!

**Comment by Basvkempen** [comment]
I removed the Phpstorm files :)

**Comment by jissereitsma** [comment]
Awesome. Many thanks. I hope to release an official build later this week.

**Comment by gety9** [comment]
@Basvkempen1 

it's showing price for some of my bundle products, and does not show for others. Trying to understand what can be the reason.
Seems like [is required](https://puu.sh/znbgI/49129f4c46.png) have to be set for the price you want to show, correct?

Also it's showing price [only for ecommerce layer](https://puu.sh/znboO/9be97e5556.png), correct?

**Comment by Basvkempen** [comment]
@gety9 its just showing the price in the datalayer I think yet. although this is beyond the scope of my changes. so @jissereitsma will have to comment on that.

I think your right about the required tag. It is impossible for the code to determine what options to use and what not. so it uses just the required onces.

I hope this helps you out !

**Comment by gety9** [comment]
@Basvkempen1 thank you for clarification

"I think your right about the required tag. It is impossible for the code to determine what options to use and what not. so it uses just the required onces."
Sure. it's logical, just wanted to check that it's how it should work or it was my bug.

"its just showing the price in the datalayer I think yet."
There are 2 price variables in data layer on product page
```
	var dataLayer = [({
        "productPrice":
```
and 
```
	dataLayer.push({
        'ecommerce': {
            "detail": [{
                "price":
```

Second one works correctly, first one no.

**Pull request merged**
